### ISSUE TITLE
PA Review: Channels

### ISSUE THREAD

**Issue by aclee91** [aclee91/Dischat#19]
Channels list, and add via the +, is mostly complete. I just need the channel title to display in the final section, where the main chat will be. If this is ok, i'm going to start making the components for the chat section.

**Comment by mashuDuek** [comment]
Hi Aarron, this looks great. 

Not re-routed to the Channel after creating. Other than that, so far so good. 

The only other thing is that I've just checked out Discord and it seems as each Channel list element, should also have a settings gear (on hover), from which we should be able to edit the name or delete the channel.

Mashu

**Comment by aclee91** [comment]
I plan on handling delete later, mainly because it would get tricky because of the dependent:destroys needed on the database side. I can work on the edit name functionality though.

**Comment by mashuDuek** [comment]
I think making the "on hover" settings gear appear, and have that display a settings component, which covers the entire page (because thats how discord does it), is something that you could do without messing around with dependent destroy. You don't have to add the functionality for the delete until you feel it's right to do so, but showing that component should be part of this feature, for sure.

**Comment by aclee91** [comment]
edit channel name/description functionality done

**Comment by mashuDuek** [comment]
Hey Aarron, 

It looks amazing! There are a couple small styling things I would point out. 
I'll slack you screenshots of what I mean. Other than that, the functionality of adding channels is great! 

The only other thing I'd point out is that the on hover edit button, should be a "settings" gear icon. 

Let me know if you have nay questions! 

Mashu

**Comment by aclee91** [comment]
restyled w/ gear button, resized channel items to be smaller, resized headers, and added better-styled # symbols
