### ISSUE TITLE
User Auth Complete

### ISSUE THREAD

**Issue by aclee91** [aclee91/Dischat#4]
see heroku, /#/login and /#/signup

**Comment by mashuDuek** [comment]
Hi Aarron, 

Looks amazing! I am super impressed! :).

One thing to change before I can close you on this first feature. Make sure that the logout button redirects you to the /login route. Just to make sure we aren't redirected to just slash, because there isn't anything on that page. 

Let me know when it redirects to the right place and I'll check off on it! 

Mashu
